export default [
  {
    id: 1,
    title: '2 Alpes Bike Park',
    image: 'https://images.pexels.com/photos/1619299/pexels-photo-1619299.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    description: 'Lorem ipsum dolor sit amet, adipiscing elit. Nullam at lacus sit amet felis...',
    address: null,
    city: '2 Alpes',
    longitude: null,
    latitude: null,
    openingHours: null,
    closedHours: null,
    saisonDate: '15 Oct. 2021',
    numbersUsers: null,
    averageRating: 6,
    difficulty: 5,
    link: 'www.les2alpes.com',
    price: 27,
    accessibility: null,
    sLike: null,
    dPositif: null,
    dNegatif: null,
    trackNumber: null,
    typeSpot: 'VTT',
    status: 1,
    createdAt: '2021-09-21T17:13:55+02:00',
    updatedAt: null,
    publishedAt: null,
    comments: [],
    categories: [],
    event: [],
    departement: null,
  },
  {
    id: 2,
    title: 'Evenement 2',
    image: 'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    description: 'Lorem ipsum dolor sit amet, adipiscing elit. Nullam at lacus sit amet felis...',
    address: null,
    city: 'Beaugency',
    longitude: null,
    latitude: null,
    openingHours: null,
    closedHours: null,
    saisonDate: '15 Oct. 2021',
    numbersUsers: null,
    averageRating: 6,
    difficulty: 5,
    link: 'www.les2alpes.com',
    price: 27,
    accessibility: null,
    sLike: null,
    dPositif: null,
    dNegatif: null,
    trackNumber: null,
    typeSpot: 'VTT',
    status: 1,
    createdAt: '2021-09-21T17:13:55+02:00',
    updatedAt: null,
    publishedAt: null,
    comments: [],
    categories: [],
    event: [],
    departement: null,
  },
  {
    id: 3,
    title: 'Evenement 3',
    image: 'https://images.pexels.com/photos/163491/bike-mountain-mountain-biking-trail-163491.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    description: 'Lorem ipsum dolor sit amet, adipiscing elit. Nullam at lacus sit amet felis...',
    address: null,
    city: 'Lailly-en-Val',
    longitude: null,
    latitude: null,
    openingHours: '08h00',
    closedHours: '18h00',
    saisonDate: '15 Oct. 2021',
    numbersUsers: null,
    averageRating: 6,
    difficulty: 5,
    link: 'www.les2alpes.com',
    price: 27,
    accessibility: null,
    sLike: null,
    dPositif: null,
    dNegatif: null,
    trackNumber: null,
    type_spot: 'VTT',
    status: 1,
    createdAt: '2021-09-21T17:13:55+02:00',
    updatedAt: null,
    publishedAt: null,
    comments: [],
    categories: [],
    event: [],
    departement: null,
  },
  {
    id: 4,
    title: 'Les gets bike park',
    image: 'https://images.pexels.com/photos/3642482/pexels-photo-3642482.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    description: 'super gets',
    address: null,
    city: 'Ville des Gets',
    longitude: null,
    latitude: null,
    openingHours: '08h00',
    closed_hours: '18h00',
    saison_date: null,
    numbers_users: null,
    average_rating: null,
    difficulty: null,
    link: 'https://www.google.com/',
    price: null,
    accessibility: null,
    s_like: null,
    d_positif: null,
    d_negatif: null,
    track_number: null,
    type_spot: 'Bike Park',
    status: 1,
    createdAt: '2021-09-21T16:09:07+02:00',
    updatedAt: null,
    publishedAt: null,
    comments: [],
    categories: [],
    event: [],
    departement: null,
  },
];
